# Generated by Django 6.0.2 on 2026-03-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0003_remove_projectapplication_new_or_amended_crls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapplication',
            name='date_archived',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
