# Generated by Django 6.0.2 on 2026-03-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0004_projectapplication_date_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapplication',
            name='drive_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
