# Generated by Django 6.0.2 on 2026-03-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0005_projectapplication_drive_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_cloud_sync', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
