# Generated by Django 6.0.2 on 2026-04-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0006_systemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('tin', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=50, null=True)),
                ('address_street', models.CharField(blank=True, max_length=255, null=True)),
                ('city_municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(default='Negros Occidental', max_length=100)),
                ('prc_accre_no', models.CharField(blank=True, max_length=100, null=True)),
                ('sp_prc_reg_validity', models.DateField(blank=True, null=True)),
                ('sn_certificate_of_reg', models.CharField(blank=True, max_length=100, null=True)),
                ('prn', models.CharField(blank=True, max_length=100, null=True)),
                ('broker_prn', models.CharField(blank=True, max_length=100, null=True)),
                ('broker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('broker_date_of_reg', models.DateField(blank=True, null=True)),
                ('broker_place_of_reg', models.CharField(blank=True, max_length=255, null=True)),
                ('or_no_registration', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_reg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('or_date', models.DateField(blank=True, null=True)),
                ('surety_bond_validity', models.DateField(blank=True, null=True)),
                ('or_no_cash_bond', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_cb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_filed', models.DateField(blank=True, null=True)),
                ('date_of_registration', models.DateField(blank=True, null=True)),
                ('date_released', models.DateField(blank=True, null=True)),
                ('released_year', models.IntegerField(blank=True, null=True)),
                ('is_renewal', models.BooleanField(default=False)),
                ('valid_years', models.JSONField(blank=True, default=list, null=True)),
                ('note', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='salesperson_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
