# Generated by Django 6.0.2 on 2026-04-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0007_salesperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='date_archived',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
