# Generated by Django 6.0.2 on 2026-04-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0008_salesperson_date_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperson',
            name='broker_name',
        ),
        migrations.AddField(
            model_name='salesperson',
            name='broker_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='broker_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='broker_middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='broker_suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
