# Generated by Django 6.0.2 on 2026-04-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0009_remove_salesperson_broker_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='reg_month_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='released_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='released_month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='released_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
