# Generated by Django 6.0.2 on 2026-04-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0012_applicationstatus_applicationtype_crlsoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
